name: workflow

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build the project
        run: npm run build

      - name: Create release package
        run: |
          mkdir release
          cp -r .next public package.json yarn.lock release/
          tar -czvf release.tar.gz release/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: release-artifact
          path: release.tar.gz

      - name: Create a new release on GitHub
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: "Release v1.0.0"
          body: |
            Automated release from pipeline. Contains:
            - Production build
            - Required public assets
          draft: false
          prerelease: false

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
