#.gitlab-ci.yml file

image: node:latest

cache:
  key: package-lock.json
  paths:
    - node_modules/
    - .npm/

stages:
  - validate
  - test
  - build
  - release
  - deploy


variables:
  ENV_TARGET: "canary"

install:
  stage: validate
  script:
    - npm ci --cache .npm --prefer-offline

lint:
  stage: validate
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: never
      allow_failure: true
  script:
    - npm run lint

only-canari:
  stage: validate
  script:
    - echo "Hello Only '$ENV_TARGET'"

.common-test-config: &common-test-config
  stage: test
  script:
    - echo "Test script"

unit-test:
  <<: *common-test-config
  script:
    - npm test

e2e-test:
  <<: *common-test-config
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - needs:
        - job: integration-test
  script:
    - echo "Hello E2E !"

integration-test:
  <<: *common-test-config
  script:
    - echo "Hello integration"
  rules:
    - needs:
        - job: unit-test

release:
  stage: release
  when: manual
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_COMMIT_TAG == null && $CI_COMMIT_TITLE !~ /^chore: release/'
  before_script:
    - git config user.email "$GITLAB_USER_EMAIL"
    - git config user.name "$GITLAB_USER_NAME"
    - git remote set-url origin "https://gitlab-ci-token:$GITLAB_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git"
    - git checkout $CI_COMMIT_BRANCH
    - git pull origin $CI_COMMIT_BRANCH --rebase
  script:
    - npx --yes release-it --ci
