# .gitlab-ci.yml file

image: node:latest
cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
    - .npm/

stages:
  - validate
  - test
  - build
  - release
  - deploy

# Anchor for common job configuration
.default-job: &default-job
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /^chore: release/'
      when: never
    - when: on_success

install:
  stage: .pre
  script:
    - npm ci --cache .npm --prefer-offline

lint:
  stage: validate
  <<: *default-job
  script:
    - npm run lint

unit-test:
  stage: test
  <<: *default-job
  script:
    - npm test

integration-test:
  stage: test
  <<: *default-job
  script:
    - echo "Hello Integration!"
  needs:
    - unit-test

release:
  stage: release
  when: manual
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_COMMIT_TAG == null && $CI_COMMIT_TITLE !~ /^chore: release/'
  before_script:
    - git config user.email $GITLAB_USER_EMAIL
    - git config user.name $GITLAB_USER_NAME
    - git remote set-url origin "https://gitlab-ci-token:$GITLAB_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git"
    - git checkout $CI_COMMIT_BRANCH
    - git pull origin $CI_COMMIT_BRANCH --rebase
  script:
    - npx --yes release-it --ci

e2e-test:
  stage: test
  <<: *default-job
  script:
    - echo "Hello E2E !"
  needs:
    - integration-test
  rules:
    - if: '$CI_MERGE_REQUEST_IID'

only-canary:
  stage: validate
  script:
    - echo "Hello Only Canary !"
  rules:
    - if: '$ENV_TARGET == "canary"'

