name: GitHub Actions CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore cached modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        run: npm ci

  validate:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore cached modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Run Lint
        run: npm run lint

  unit-test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore cached modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

  integration-test:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore cached modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        run: npm ci

      - name: Run Integration Tests
        run: echo "Running integration tests"

  e2e-test:
    if: "github.event_name == 'pull_request'"
    runs-on: ubuntu-latest
    needs: integration-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Restore cachedmodules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      
      - name: Install Dependencies
        run: npm ci 
      
      - name: Run E2E Tests
        run: echo "E2E tests" 

  release:
    runs-on: ubuntu-latest
    needs: [validate, unit-test]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
            
    - name: Cache Node modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-
            
    - name: config
      run: |
        git config user.email "${{ vars.GIT_USER_EMAIL }}"
        git config user.name "${{ vars.GIT_USER_NAME }}"
        git remote set-url origin "https://x-access-token:${{ secrets.RELEASE_IT_TOKEN }}@github.com/${{ github.repository }}"
            
    - name: Pull Changes
      run: |
        git checkout main
        git pull origin main --rebase
            
    - name: Release
      run: npx --yes release-it --ci