image: node:latest
cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
    - .npm/
stages:
  - install
  - validate
  - test
  - build
  - release
  - deploy

install:
  stage: install
  script:
    # define cache dir & use it npm!
    - npm ci --cache .npm --prefer-offline
lint:
  stage: validate
  script:
    - npm run lint
  rules:
    - if: 
        '$CI_COMMIT_TAG == null
        && $CI_COMMIT_TITLE !~ /^chore: release/'

only-canary:
  stage: validate
  script:
    - echo "Hello Only Canary !"
  rules:
    - if: '$ENV_TARGET == "canary"'

unit-test:
  stage: test
  script:
    - npm test
  rules:
    - if: 
        '$CI_COMMIT_TAG == null
        && $CI_COMMIT_TITLE !~ /^chore: release/'

integration-test:
  stage: test
  script:
    - echo "Hello Integration !"
  dependencies:
    - unit-test
  rules:
    - if: '$CI_COMMIT_TAG == null && $CI_COMMIT_TITLE !~ /^chore: release/'


e2e-test:
  stage: test
  script:
    - echo "Hello E2E!"
  dependencies:
    - integration-test
  rules:
    - if: '$CI_MERGE_REQUEST_ID'

release:
  stage: release
  when: manual
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"
        && $CI_COMMIT_TAG == null
        && $CI_COMMIT_TITLE !~ /^chore: release/'
  before_script:
    - git config user.email $GITLAB_USER_EMAIL
    - git config user.name 'OUKOUKES'
    - git remote set-url origin
      "https://gitlab-ci-token:$GITLAB_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git"
    - git checkout $CI_COMMIT_BRANCH
    - git pull origin $CI_COMMIT_BRANCH --rebase
  script:
    - npx --yes release-it --ci