name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  # Job de build
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Configurer Node.js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Utiliser la version spécifique de Node.js
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline

      - name: Validate code
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Build for production
        run: npm run build

      # Télécharger l'artefact (dist)
      - uses: actions/upload-artifact@v2
        with:
          name: web
          path: ./dist
  unit-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm test
  release:
    runs-on: ubuntu-latest
    needs: build  
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'  
    steps:
      - uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config user.email "${{ secrets.GIT_EMAIL }}"
          git config user.name "${{ secrets.GIT_USERNAME }}"
          git remote set-url origin "https://github.com/${{ github.repository }}.git"
      
      - name: Set up Node.js for release
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install release-it
        run: npm install --save-dev release-it

      - name: Create release
        run: |
          npx --yes release-it --ci

      - name: Push changes
        run: git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

