name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline
  lint:
    if: "!contains(github.event.head_commit.message, 'chore: release') && github.event_name != 'push' || (github.event_name == 'push' && github.ref_type != 'tag')"
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline
      - name: Run lint
        run: npm run lint
  unit-test:
    if: "!contains(github.event.head_commit.message, 'chore: release') && github.event_name != 'push' || (github.event_name == 'push' && github.ref_type != 'tag')"
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test